import json
import re

import requests

from backend.app.services.ollama_service import (
    MODEL_NAME,
    OLLAMA_URL,
    parse_ai_json,
)


# ============================================================
# BASIC HELPERS
# ============================================================

def _safe_json(value):
    """
    Convert a Python value into readable JSON for the LLM prompt.
    """
    try:
        return json.dumps(
            value,
            indent=2,
            ensure_ascii=False,
        )
    except (TypeError, ValueError):
        return "[]"


def _extract_ruff_issues(ruff_report):
    """
    Keep only useful Ruff information.
    """

    issues = []

    for issue in ruff_report.get("issues", []):

        if not isinstance(issue, dict):
            continue

        location = issue.get(
            "location",
            {},
        )

        if not isinstance(location, dict):
            location = {}

        issues.append(
            {
                "code": issue.get("code"),
                "message": issue.get("message"),
                "line": location.get("row"),
                "column": location.get("column"),
            }
        )

    return issues


def _extract_bandit_issues(bandit_report):
    """
    Keep only useful Bandit information.
    """

    issues = []

    for issue in bandit_report.get(
        "security_issues",
        [],
    ):

        if not isinstance(issue, dict):
            continue

        issues.append(
            {
                "test_id": issue.get("test_id"),
                "severity": issue.get("severity"),
                "confidence": issue.get("confidence"),
                "line": issue.get("line"),
                "problem": issue.get("problem"),
            }
        )

    return issues


def _extract_semantic_issues(semantic_report):
    """
    Keep only useful semantic-review findings.

    Semantic findings are generated by the LLM and therefore
    must be treated as evidence that needs to be considered,
    not blindly trusted.
    """

    if not isinstance(
        semantic_report,
        dict,
    ):
        return []

    issues = semantic_report.get(
        "issues",
        [],
    )

    if not isinstance(
        issues,
        list,
    ):
        return []

    normalized = []

    for issue in issues:

        if not isinstance(
            issue,
            dict,
        ):
            continue

        normalized.append(
            {
                "category": issue.get(
                    "category"
                ),
                "severity": issue.get(
                    "severity"
                ),
                "confidence": issue.get(
                    "confidence"
                ),
                "line": issue.get(
                    "line"
                ),
                "end_line": issue.get(
                    "end_line"
                ),
                "problem": issue.get(
                    "problem"
                ),
                "evidence": issue.get(
                    "evidence"
                ),
                "why": issue.get(
                    "why"
                ),
                "verification": issue.get(
                    "verification"
                ),
                "change": issue.get(
                    "change"
                ),
            }
        )

    return normalized


# ============================================================
# BANDIT EXPLANATION
# ============================================================

def build_bandit_explanation_prompt(
    bandit_report,
    source_code,
):
    """
    Build a prompt for explaining Bandit findings.

    This does NOT generate the complete corrected program.
    """

    issues = _extract_bandit_issues(
        bandit_report
    )

    return f"""
You are a senior Python security engineer.

Explain the Bandit findings below using ONLY the original
source code.

Do not invent behavior.

For every finding explain:

- what is wrong
- why it matters
- how it should be fixed
- the relevant source-code behavior

If the finding is not actually applicable to the source,
say so rather than inventing a problem.

Return ONLY valid JSON.

Required structure:

{{
    "security_issues": [
        {{
            "test_id": "...",
            "severity": "...",
            "confidence": "...",
            "line": 1,
            "problem": "...",
            "why": "...",
            "fix": "..."
        }}
    ]
}}

ORIGINAL SOURCE:

{source_code}

BANDIT FINDINGS:

{_safe_json(issues)}
"""


def explain_bandit_report(
    bandit_report,
    source_code,
):
    """
    Add AI explanations to Bandit findings.
    """

    issues = _extract_bandit_issues(
        bandit_report
    )

    if not issues:
        return bandit_report

    prompt = build_bandit_explanation_prompt(
        bandit_report,
        source_code,
    )

    try:

        response = requests.post(
            OLLAMA_URL,
            json={
                "model": MODEL_NAME,
                "prompt": prompt,
                "stream": False,
                "format": "json",
                "options": {
                    "temperature": 0,
                    "num_predict": 1200,
                },
            },
            timeout=120,
        )

        response.raise_for_status()

        data = response.json()

        ai_response = data.get(
            "response",
            "",
        ).strip()

        if not ai_response:
            return bandit_report

        parsed = parse_ai_json(
            ai_response
        )

        if not isinstance(
            parsed,
            dict,
        ):
            return bandit_report

        explanations = parsed.get(
            "security_issues",
            [],
        )

        if not isinstance(
            explanations,
            list,
        ):
            return bandit_report

        # Match explanations back to Bandit issues.
        for index, issue in enumerate(
            bandit_report.get(
                "security_issues",
                [],
            )
        ):

            if index >= len(
                explanations
            ):
                break

            explanation = explanations[
                index
            ]

            if not isinstance(
                explanation,
                dict,
            ):
                continue

            issue["why"] = explanation.get(
                "why",
                issue.get("why", ""),
            )

            issue["fix"] = explanation.get(
                "fix",
                issue.get("fix", ""),
            )

        return bandit_report

    except (
        requests.exceptions.RequestException,
        ValueError,
        TypeError,
    ):

        return bandit_report


# ============================================================
# RUFF EXPLANATION
# ============================================================

def build_ruff_explanation_prompt(
    ruff_report,
    source_code,
):
    """
    Build a prompt for explaining Ruff findings.
    """

    issues = _extract_ruff_issues(
        ruff_report
    )

    return f"""
You are a senior Python code-quality engineer.

Explain the Ruff findings below using ONLY the original
source code.

Important:

A Ruff finding is not necessarily the most important problem
in the program.

Do not allow a stylistic Ruff suggestion to hide a correctness,
security, performance, or concurrency problem.

Do not invent behavior.

Return ONLY valid JSON.

Required structure:

{{
    "issues": [
        {{
            "code": "...",
            "line": 1,
            "problem": "...",
            "why": "...",
            "fix": "..."
        }}
    ]
}}

ORIGINAL SOURCE:

{source_code}

RUFF FINDINGS:

{_safe_json(issues)}
"""


def explain_ruff_report(
    ruff_report,
    source_code,
):
    """
    Add AI explanations to Ruff findings.
    """

    issues = _extract_ruff_issues(
        ruff_report
    )

    if not issues:
        return ruff_report

    prompt = build_ruff_explanation_prompt(
        ruff_report,
        source_code,
    )

    try:

        response = requests.post(
            OLLAMA_URL,
            json={
                "model": MODEL_NAME,
                "prompt": prompt,
                "stream": False,
                "format": "json",
                "options": {
                    "temperature": 0,
                    "num_predict": 1000,
                },
            },
            timeout=120,
        )

        response.raise_for_status()

        data = response.json()

        ai_response = data.get(
            "response",
            "",
        ).strip()

        if not ai_response:
            return ruff_report

        parsed = parse_ai_json(
            ai_response
        )

        if not isinstance(
            parsed,
            dict,
        ):
            return ruff_report

        explanations = parsed.get(
            "issues",
            [],
        )

        if not isinstance(
            explanations,
            list,
        ):
            return ruff_report

        for index, issue in enumerate(
            ruff_report.get(
                "issues",
                [],
            )
        ):

            if index >= len(
                explanations
            ):
                break

            explanation = explanations[
                index
            ]

            if not isinstance(
                explanation,
                dict,
            ):
                continue

            issue["why"] = explanation.get(
                "why",
                issue.get("why", ""),
            )

            issue["fix"] = explanation.get(
                "fix",
                issue.get("fix", ""),
            )

        return ruff_report

    except (
        requests.exceptions.RequestException,
        ValueError,
        TypeError,
    ):

        return ruff_report


# ============================================================
# COMPLETE FIX PROMPT
# ============================================================

def build_complete_fix_prompt(
    source_code,
    bandit_report,
    ruff_report,
    semantic_report=None,
):
    """
    Build the prompt for generating ONE complete corrected
    Python program.

    The AI receives three independent sources:

        1. Bandit
        2. Ruff
        3. Semantic LLM review

    The semantic review is particularly important for:
        - logic bugs
        - edge cases
        - performance
        - concurrency
        - resource management
        - authentication logic
        - business-flow mistakes
    """

    if semantic_report is None:
        semantic_report = {
            "issues": []
        }

    security_issues = (
        _extract_bandit_issues(
            bandit_report
        )
    )

    ruff_issues = (
        _extract_ruff_issues(
            ruff_report
        )
    )

    semantic_issues = (
        _extract_semantic_issues(
            semantic_report
        )
    )

    return f"""
You are a senior Python software engineer performing
a complete, behavior-preserving code correction.

You must inspect the ORIGINAL SOURCE CODE and ALL
reported findings.

There are three independent sources of findings:

1. Bandit
2. Ruff
3. Semantic code review

Your job is to determine which findings represent real
problems and generate ONE complete corrected Python program
when a safe correction is possible.

============================================================
CRITICAL PRIORITY RULE
============================================================

Do NOT blindly follow Ruff.

Ruff detects many useful code-quality problems, but some
Ruff findings are stylistic or secondary.

A real:

- security vulnerability
- authentication bug
- authorization bug
- correctness bug
- runtime failure
- data corruption problem
- concurrency problem
- important edge case

must take priority over a stylistic Ruff recommendation.

Example:

Original:

    if username in users:
        if password:
            return True

Ruff may recommend:

    if username in users and password:
        return True

DO NOT consider that a complete fix.

The real semantic problem is that the password is not
compared against the stored credential.

A correct fix must address the actual behavior.

============================================================
ISSUE PRIORITY
============================================================

Prioritize issues approximately in this order:

1. CRITICAL security
2. HIGH security
3. CRITICAL correctness bugs
4. HIGH correctness bugs
5. CRITICAL concurrency/data-loss issues
6. HIGH concurrency issues
7. important edge cases
8. MEDIUM correctness bugs
9. important performance problems
10. resource/database problems
11. Ruff correctness issues
12. Ruff maintainability/style issues

Do NOT introduce unnecessary changes merely to satisfy
a low-priority style recommendation.

============================================================
SEMANTIC FINDINGS ARE IMPORTANT
============================================================

Semantic findings may identify problems that Bandit and Ruff
cannot detect.

Examples include:

- division by zero from a specific execution path
- authentication bypass
- incorrect password comparison
- O(n²) algorithms
- mutable default arguments
- race conditions
- resource leaks
- incorrect business logic
- missing edge cases

You MUST inspect semantic findings against the ORIGINAL
SOURCE CODE.

Do not blindly trust them.

If a semantic finding is supported by the source code,
address it.

If it contradicts the source code, do not implement it.

============================================================
BEHAVIOR PRESERVATION
============================================================

Rules:

1. Preserve original behavior whenever safely possible.

2. Do not invent business requirements.

3. Do not invent missing values.

4. Do not invent credentials.

5. Do not invent function arguments.

6. Do not invent commands.

7. Do not invent database schema.

8. Do not invent API responses.

9. Do not rewrite working code unnecessarily.

10. Do not remove functionality merely to make a scanner pass.

============================================================
F821 RULE
============================================================

For F821:

- Inspect the ORIGINAL SOURCE CODE.
- Do not invent a value.
- Do not replace an undefined variable with:
  0, 1, 5, 10, None, "", or another guessed value.

However, obvious typos may be safely corrected.

Example:

    rang(10)

when the surrounding source clearly requires:

    range(10)

may be corrected.

But:

    print(total)

when no definition or intended source for total exists
must NOT be guessed.

In that situation return:

"corrected_code": ""

and explain that manual developer input is required.

============================================================
SECURITY
============================================================

Fix genuine security problems including:

- SQL injection
- command injection
- shell=True
- unsafe eval/exec
- hardcoded passwords
- hardcoded API keys
- plaintext credentials
- insecure randomness
- path traversal
- unsafe deserialization
- authentication bypass
- authorization problems
- sensitive information exposure

Do not replace security problems with unrelated behavior.

============================================================
PASSWORDS AND SECRETS
============================================================

Never leave hardcoded passwords, tokens, API keys,
credentials, or secrets in corrected_code.

Do not use hardcoded fallbacks.

Never generate:

    os.getenv("PASSWORD", "password")

or:

    os.getenv("PASSWORD", "admin123")

or equivalent.

Prefer:

    import os

    password = os.getenv("APP_PASSWORD")

    if password is None:
        raise RuntimeError(
            "APP_PASSWORD environment variable is required"
        )

Do not expose the original secret in:

- comments
- strings
- variable names
- error messages
- documentation
- fallback values

============================================================
AUTHENTICATION
============================================================

For authentication code:

Do not merely make the condition syntactically cleaner.

Verify that credentials are actually compared.

For example:

BAD:

    if username in users:
        if password:
            return True

A valid semantic correction must compare the supplied
credential against the stored credential.

However, do not invent an entire authentication system
if the source code does not provide enough context.

If plaintext password storage is present, recognize that
as a security problem.

============================================================
SQL
============================================================

Use parameterized queries when user-controlled values
are inserted into SQL.

For example:

    query = "SELECT * FROM users WHERE username = ?"
    cursor.execute(query, (username,))

Do not merely modify formatting.

If the source opens a database connection and does not
release it, consider whether a context manager can safely
preserve the behavior.

============================================================
SUBPROCESS
============================================================

Avoid shell=True when unnecessary.

Prefer argument lists.

Example:

    subprocess.run(
        args,
        check=True,
    )

But do NOT invent the command structure.

If the same user-controlled input is used for:

- eval/exec
- shell execution
- subprocess execution

and the intended behavior cannot be safely determined,
do NOT invent a replacement.

Return:

    "corrected_code": ""

and explain that manual review is required.

============================================================
EVAL
============================================================

Use ast.literal_eval ONLY when the source clearly expects
Python literals.

Do not claim literal_eval can execute arbitrary Python
expressions.

If the source intentionally evaluates arbitrary Python
expressions and the intended behavior cannot be established,
manual review is required.

============================================================
PERFORMANCE
============================================================

Address meaningful algorithmic problems.

Example:

Nested pairwise comparison:

    for i in range(len(numbers)):
        for j in range(i + 1, len(numbers)):

may indicate O(n²).

If the actual behavior can be preserved using a set,
a set-based implementation may be appropriate.

Do not optimize code merely because another algorithm
exists.

============================================================
CONCURRENCY
============================================================

For shared mutable state accessed by multiple threads,
inspect synchronization carefully.

Do not claim that every multi-threaded operation is unsafe.

If the source clearly has shared mutable state with no
appropriate synchronization and a lock can safely preserve
the behavior, a lock may be introduced.

============================================================
MUTABLE DEFAULTS
============================================================

For:

    def add_item(item, items=[]):

prefer:

    def add_item(item, items=None):
        if items is None:
            items = []

Do not change explicitly supplied lists.

============================================================
EMPTY INPUT
============================================================

If the source clearly allows an empty input and later
performs an operation such as:

    total / len(numbers)

identify the runtime failure.

Do NOT invent whether the correct business behavior should be:

- return 0
- return None
- raise ValueError
- another result

unless the source provides enough context.

If the structural correction is clear but the desired
business behavior is ambiguous, manual review may be required.

============================================================
RUFF STYLE
============================================================

Do not prioritize style over correctness.

For example:

SIM102:

    if a:
        if b:
            ...

may be combined.

But if the code contains an authentication bug, fix the
authentication bug first.

Do not introduce behavior changes merely to satisfy style.

============================================================
COMPLETE PROGRAM
============================================================

If a safe correction is possible:

"corrected_code" MUST contain the COMPLETE Python program.

Do not return only changed lines.

Do not return:

    ...

Do not return:

    TODO

Do not return placeholders.

Do not remove unrelated working code.

============================================================
MANUAL REVIEW
============================================================

Return:

{{
    "summary": "Manual review is required.",
    "fix": "Explain exactly why the intended behavior cannot be safely determined.",
    "corrected_code": "",
    "manual_review_required": true
}}

when:

- the required behavior is genuinely ambiguous
- fixing the issue requires inventing business logic
- an undefined variable cannot be resolved
- an unsafe command cannot be safely reconstructed
- eval behavior cannot be safely determined
- multiple incompatible interpretations are possible

Do NOT use manual review merely because an obvious typo
can safely be corrected.

============================================================
OUTPUT
============================================================

Return ONLY valid JSON.

Required structure:

{{
    "summary": "...",
    "fix": "...",
    "corrected_code": "...",
    "manual_review_required": false
}}

If manual review is required:

{{
    "summary": "Manual review is required.",
    "fix": "...",
    "corrected_code": "",
    "manual_review_required": true
}}

Do not return markdown.

Do not return ```json.

Do not return explanations outside JSON.

============================================================
FINAL SELF-CHECK
============================================================

Before returning:

1. Did you inspect the ORIGINAL source?

2. Did you inspect Bandit?

3. Did you inspect Ruff?

4. Did you inspect semantic findings?

5. Did you prioritize real security/correctness problems?

6. Did you avoid blindly following Ruff style suggestions?

7. Did you preserve behavior?

8. Did you avoid inventing values?

9. Did you avoid inventing arguments?

10. Did you avoid inventing commands?

11. Did you fix all applicable high-priority findings?

12. Did you avoid unrelated changes?

13. Is corrected_code complete?

14. Is corrected_code valid Python?

15. Are hardcoded secrets removed?

16. Are secret fallbacks removed?

17. Did you avoid guessed F821 values?

18. Did you avoid unsafe replacements for eval/subprocess?

19. If behavior is ambiguous, did you return manual review?

============================================================
ORIGINAL SOURCE CODE
============================================================

{source_code}

============================================================
BANDIT FINDINGS
============================================================

{_safe_json(security_issues)}

============================================================
RUFF FINDINGS
============================================================

{_safe_json(ruff_issues)}

============================================================
SEMANTIC FINDINGS
============================================================

{_safe_json(semantic_issues)}
"""


# ============================================================
# COMPLETE FIX GENERATOR
# ============================================================

def generate_complete_fix(
    source_code,
    bandit_report,
    ruff_report,
    semantic_report=None,
):
    """
    Generate one complete corrected Python program.

    The AI receives:

        Original source
        +
        Bandit findings
        +
        Ruff findings
        +
        Semantic findings

    This function does NOT automatically trust the generated
    code. The caller must run AI safety and final validation.
    """

    prompt = build_complete_fix_prompt(
        source_code=source_code,
        bandit_report=bandit_report,
        ruff_report=ruff_report,
        semantic_report=semantic_report,
    )

    try:

        print(
            "\n========== COMPLETE AI FIX REQUEST =========="
        )

        response = requests.post(
            OLLAMA_URL,
            json={
                "model": MODEL_NAME,
                "prompt": prompt,
                "stream": False,
                "format": "json",
                "options": {
                    "temperature": 0,
                    "num_predict": 3000,
                },
            },
            timeout=180,
        )

        response.raise_for_status()

        data = response.json()

        ai_response = data.get(
            "response",
            "",
        ).strip()

        if not ai_response:

            print(
                "\n⚠️ AI returned an empty response."
            )

            return {
                "summary": (
                    "The AI returned an empty response."
                ),
                "fix": (
                    "No corrected code was generated."
                ),
                "corrected_code": "",
                "manual_review_required": True,
            }

        print(
            "\n========== RAW COMPLETE AI RESPONSE =========="
        )

        print(ai_response)

        parsed = parse_ai_json(
            ai_response
        )

        if not isinstance(
            parsed,
            dict,
        ):

            print(
                "\n⚠️ AI response could not be parsed."
            )

            return {
                "summary": (
                    "The AI returned an invalid response."
                ),
                "fix": (
                    "The complete AI fix could not be parsed."
                ),
                "corrected_code": "",
                "manual_review_required": True,
            }

        corrected_code = parsed.get(
            "corrected_code",
            "",
        )

        if corrected_code is None:
            corrected_code = ""

        corrected_code = str(
            corrected_code
        )

        summary = str(
            parsed.get(
                "summary",
                "",
            )
        )

        fix = str(
            parsed.get(
                "fix",
                "",
            )
        )

        manual_review_required = parsed.get(
            "manual_review_required",
            False,
        )

        if not isinstance(
            manual_review_required,
            bool,
        ):
            manual_review_required = False

        # ----------------------------------------------------
        # If the AI explicitly requires manual review,
        # do not override it.
        # ----------------------------------------------------

        if manual_review_required:

            return {
                "summary": (
                    summary
                    or "Manual review is required."
                ),
                "fix": (
                    fix
                    or (
                        "The AI could not safely "
                        "determine the intended behavior."
                    )
                ),
                "corrected_code": "",
                "manual_review_required": True,
            }

        # ----------------------------------------------------
        # Empty corrected code
        # ----------------------------------------------------

        if not corrected_code.strip():

            return {
                "summary": (
                    summary
                    or "No corrected code was generated."
                ),
                "fix": (
                    fix
                    or (
                        "The AI did not provide "
                        "corrected code."
                    )
                ),
                "corrected_code": "",
                "manual_review_required": True,
            }

        return {
            "summary": summary,
            "fix": fix,
            "corrected_code": corrected_code,
            "manual_review_required": False,
        }

    except requests.exceptions.Timeout:

        print(
            "\n⚠️ Complete AI fix request timed out."
        )

        return {
            "summary": (
                "The AI fix request timed out."
            ),
            "fix": (
                "The local LLM did not complete "
                "the correction within the allowed time."
            ),
            "corrected_code": "",
            "manual_review_required": True,
        }

    except requests.exceptions.ConnectionError:

        print(
            "\n⚠️ Could not connect to Ollama."
        )

        return {
            "summary": (
                "Could not connect to the local AI model."
            ),
            "fix": (
                "Make sure Ollama is running and "
                "the configured model is available."
            ),
            "corrected_code": "",
            "manual_review_required": True,
        }

    except requests.exceptions.RequestException as e:

        print(
            f"\n⚠️ Complete AI fix request failed: {e}"
        )

        return {
            "summary": (
                "The AI fix request failed."
            ),
            "fix": (
                "The local AI service returned "
                "a request error."
            ),
            "corrected_code": "",
            "manual_review_required": True,
        }

    except Exception as e:

        print(
            f"\n⚠️ Unexpected AI fix error: {e}"
        )

        return {
            "summary": (
                "An unexpected error occurred "
                "while generating the AI fix."
            ),
            "fix": (
                "The correction could not be safely generated."
            ),
            "corrected_code": "",
            "manual_review_required": True,
        }


# ============================================================
# F821 AMBIGUITY DETECTION
# ============================================================

KNOWN_SAFE_TYPO_REPLACEMENTS = {
    "rang": "range",
    "lenght": "length",
    "pritn": "print",
    "prnit": "print",
    "strng": "string",
}


def has_ambiguous_ruff_issues(
    ruff_report,
):
    """
    Determine whether Ruff contains an F821 issue that cannot
    be safely resolved.

    Known obvious typos such as:

        rang -> range

    are considered safe.

    Unknown undefined identifiers such as:

        total

    remain ambiguous.

    IMPORTANT:

    This function does NOT mean the entire AI review must stop.

    It only informs the caller that an F821 issue needs special
    attention.
    """

    print(
        "\n========== F821 AMBIGUITY CHECK =========="
    )

    for issue in ruff_report.get(
        "issues",
        [],
    ):

        if not isinstance(
            issue,
            dict,
        ):
            continue

        code = issue.get(
            "code"
        )

        if code != "F821":
            continue

        message = str(
            issue.get(
                "message",
                "",
            )
        )

        print(
            f"F821 message: {message}"
        )

        # ----------------------------------------------------
        # Ruff normally produces:
        #
        # Undefined name `total`
        #
        # or:
        #
        # Undefined name 'total'
        # ----------------------------------------------------

        match = re.search(
            r"Undefined name [`']([^`']+)[`']",
            message,
        )

        if not match:

            print(
                "Could not determine undefined identifier."
            )

            return True

        name = match.group(1)

        # ----------------------------------------------------
        # Known safe typo
        # ----------------------------------------------------

        if name in KNOWN_SAFE_TYPO_REPLACEMENTS:

            replacement = (
                KNOWN_SAFE_TYPO_REPLACEMENTS[
                    name
                ]
            )

            print(
                f"Detected known typo: "
                f"{name} -> {replacement}"
            )

            continue

        # ----------------------------------------------------
        # Unknown identifier
        # ----------------------------------------------------

        print(
            f"Unknown undefined name: {name}"
        )

        print(
            "The AI must determine whether this can be "
            "safely resolved."
        )

        return True

    return False